name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: digreatbrian/buildozer-action@v2
        with:
          buildozer_version: stable
          command: buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: ElimuYetuUniverse-APK
          path: bin/*.apk