name: Build APK
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04  # 22.04 ni stable zaidi ya latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Build APK
        uses: digreatbrian/buildozer-action@v2
        with:
          buildozer_version: stable
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ElimuYetApp-APK
          path: bin/*.apk
